name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
      - name: date
        run: |
          echo "Hello World!" |
          date

#  display_date_job:
#    steps:
#      - name: Now it is
#        run: |
#          date
